# Generated by Django 5.2.6 on 2025-09-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giphy_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('preview_url', models.URLField()),
                ('original_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stickerbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Start Date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stickers', models.ManyToManyField(blank=True, related_name='stickerbooks', to='main_app.sticker')),
            ],
        ),
    ]
