# Generated by Django 5.2.6 on 2025-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerbook',
            name='owner',
        ),
        migrations.AddField(
            model_name='stickerbook',
            name='description',
            field=models.TextField(default='the default sentence.', max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='stickerbook',
            name='stickers',
        ),
        migrations.AddField(
            model_name='stickerbook',
            name='stickers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
