# Generated by Django 5.2.6 on 2025-09-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_stickerbook_owner_stickerbook_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='stickerbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.stickerbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stickerbook',
            name='stickers',
            field=models.ImageField(blank=True, null=True, upload_to='stickers/'),
        ),
    ]
