# Generated by Django 5.2.6 on 2025-09-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sticker_stickerbook_alter_stickerbook_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerbook',
            name='stickers',
        ),
    ]
