# Generated by Django 5.2.6 on 2025-09-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_stickerbook_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='giphy_id',
        ),
    ]
